### ISSUE TITLE
MET filters reconfiguring

### ISSUE THREAD

**Issue by JoramBerger** [KappaAnalysis/Kappa#10]
The MET filters should be configured for 13 TeV again according to official recommendations when available:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2015#ETmiss_filters
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2

The [producer](https://github.com/KappaAnalysis/Kappa/blob/master/Producers/interface/KFilterSummaryProducer.h) might need an update.

**Comment by rfriese** [comment]
changed in 2016 miniaod
