### ISSUE TITLE
Use KParticles for packed candidates

### ISSUE THREAD

**Issue by JoramBerger** [KappaAnalysis/Kappa#13]
The [KPackedPFCandidateProducer](https://github.com/KappaAnalysis/Kappa/blob/master/Producers/interface/KPackedPFCandidateProducer.h) writes out KPFCandidates. However, the typical PFCandidate quantities (hcalEnergy, ecalEnergy, deltaP) are not filled. In this case, a KPFCandidate does not make sense. A KParticle would save about 40% of the skimming space of this collection and contain the same information.

**Comment by rfriese** [comment]
Are you sure there really is potential for saving space? I thought root compresses variables that aren't filled.

I think it's rather confusing when a pf candidates collection has not the form KPFCandidate but something else.
