### ISSUE TITLE
KGenInfoProducer reading from run before endRun

### ISSUE THREAD

**Issue by rcaspart** [KappaAnalysis/Kappa#16]
Hi,

during the work on making Kappa compatible with CMSSW_7_6 I also stumbled upon one potential future problem which might cause Kappa to become incompatible once more.
Some of you might have noticed that when running a Kappa skim you get warnings like this [I]. This is caused by the KGenInfoPruducer which in the function onlumi accesses the GenRunInfoProduct of the run the lumi-section is in[II].
Sofar this works perfectly fine and has (as far as I understand) only the caveat that the content of the GenRunInfoProduct might potentially change in the time until the run ends.
However this procedure does not work anymore when switching from getByLabel to getByToken (which is the method recommended for future use) as there such accesses are forced to happen only in the endRun function. 
Apparently there is some discussion going on about this [III] which I guess we should keep an eye on it in order to react in case needed.

cheers,
Rene

[I]
%MSG-w LogicError:  KTuple:kappatuple@beginLumi 14-Jan-2016 17:22:13 CET  Run: 1 Lumi: 17
::getByLabel: An attempt was made to read a Run product before endRun() was called.
The product is of type 'GenRunInfoProduct'.
The specified ModuleLabel was 'generator'.
The specified productInstanceName was ''.

%MSG
[II] https://github.com/KappaAnalysis/Kappa/blob/master/Producers/interface/KGenInfoProducer.h#L51-L52
[III] https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3437/1.html

**Comment by rfriese** [comment]
what do you think: should we switch to getByToken anyway consistently in Kappa?

**Comment by greyxray** [comment]
I would vote yes - after all this is an official recommendation

**Comment by rfriese** [comment]
yes, you're right. A quick check of the 66 times getByLabel is called showed me that some of them might be even completely useless, so I can do some cleaning.

I'll do this change once the 92X branch is merged

**Comment by rfriese** [comment]
okay, so the only feasible way is to introduce a third tree "Run" apart from Event and Lumi Trees... This will be another major change, but I'll make a proposal depending on the getByToken Tree.

It will also affect all later linked code like KappaTools and Artus.

**Comment by greyxray** [comment]
Dear Raphael, 

sorry for the late notice. Could you give a short summary for me and others who are not so close acknowledged with cmssw why we actually need to also have the "Run" tree after the switching to the "getToken"s?

Cheers, Olena

**Comment by rcaspart** [comment]
Hi Olena,

the point is (as discussed in the hypernews I linked in the first post) that reading from the runProduct before the endRun (i.e. before the run is actually finished) was only semi-supported for quite some time now.
For getByLabel it worked, although it gives the warning stated above and has the potential danger of the runProduct changing after we read it.
With getByToken reading the runProduct before the endRun is (afaik) impossible. As a consequence, we need to access the runProduct only after the endRun.
For Kappa the most clean way (which came to mind) to do this and store the corresponding information, is to introduce a new run tree which gets filled in the endRun function.

Cheers, Rene
