### ISSUE TITLE
Restriction to 64 HLTs

### ISSUE THREAD

**Issue by thomas-mueller** [KappaAnalysis/Kappa#2]
Dear Kappa experts,

In the HTT there are problems with the restriction to 64 trigger bits in Kappa. Currently we use the following settings:

hltWhitelist = cms.vstring( ## HLT selection
    "^HLT_._Mu[0-9]+.__v[0-9]+$",
    "^HLT_._Ele[0-9]+.__v[0-9]+$",
    "^HLT_._Tau[0-9]+.__v[0-9]+$",
)

hltBlacklist = cms.vstring(
    "^HLT_._Mu300.__v[0-9]+$",
    "^HLT_._Mu350.__v[0-9]+$",
    "^HLT_._Ele105.__v[0-9]+$",
    "^HLT_._Ele115.__v[0-9]+$",
    "^HLT_._Photon.__v[0-9]+$",
    "^HLT_._photon.__v[0-9]+$",
    "^HLT_._Jet.__v[0-9]+$",
    "^HLT_._jet.__v[0-9]+$",
    "^HLT_._MET.__v[0-9]+$",
    "^HLT_._Psi.__v[0-9]+$",
    "^HLT_._Mass.__v[0-9]+$",
    "^HLT_._HT[0-9]+.__v[0-9]+$",
    "^HLT_L1.__v[0-9]+$",
    "^HLT_L2.__v[0-9]+$",
    "^HLT_L1L2.*_v[0-9]+$",
    "^HLT_._SameSign.__v[0-9]+$",
    "^HLT_._NoVertex.__v[0-9]+$",
    "^HLT_._NoVtx.__v[0-9]+$",
    "^HLT_._NoFilters.__v[0-9]+$",
    "^HLT_._SaveObjects.__v[0-9]+$",
    "^HLT_.__Di.__v[0-9]+$",
    "^HLT_.__Double.__v[0-9]+$",
    "^HLT_.__Bs.__v[0-9]+$",
    "^HLT_.__DZ.__v[0-9]+$",
    "^HLT_._Onia.__v[0-9]+$",
    "^HLT_._WHbbBoost.__v[0-9]+$",
    "^HLT_._dEta.__v[0-9]+$",
    "^HLT_._DiMu[0-9]+_Ele[0-9]+.__v[0-9]+$",
)

As you see, the blacklist items are already quite "special". This is because taking just all Mu/Ele/Tau triggers results in slightly more than 64 triggers, that Kappa currently cannot store. As an example, in run 2 data the settings above yield the following 63 matches:

HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v1
HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_v2
HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v2
HLT_DoubleMediumIsoPFTau40_Trk1_eta2p1_Reg_v2
HLT_Ele22_eta2p1_WPLoose_Gsf_v1
HLT_Ele22_eta2p1_WPTight_Gsf_v1
HLT_Ele22_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v1
HLT_Ele27_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v1
HLT_Ele27_eta2p1_WPLoose_Gsf_v1
HLT_Ele27_eta2p1_WPTight_Gsf_v1
HLT_Ele32_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v1
HLT_Ele32_eta2p1_WPLoose_Gsf_v1
HLT_Ele32_eta2p1_WPTight_Gsf_v1
HLT_IsoMu17_eta2p1_v2
HLT_IsoMu17_eta2p1_LooseIsoPFTau20_v2
HLT_IsoMu17_eta2p1_LooseIsoPFTau20_SingleL1_v2
HLT_IsoMu17_eta2p1_MediumIsoPFTau40_Trk1_eta2p1_Reg_v2
HLT_DoubleIsoMu17_eta2p1_v2
HLT_IsoMu24_eta2p1_LooseIsoPFTau20_v2
HLT_IsoMu20_v2
HLT_IsoMu20_eta2p1_v2
HLT_IsoMu24_eta2p1_v2
HLT_IsoMu27_v2
HLT_IsoTkMu20_v2
HLT_IsoTkMu20_eta2p1_v2
HLT_IsoTkMu24_eta2p1_v2
HLT_IsoTkMu27_v2
HLT_LooseIsoPFTau50_Trk30_eta2p1_v2
HLT_Mu17_Mu8_v1
HLT_Mu20_Mu10_v1
HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v2
HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v2
HLT_Mu27_TkMu8_v2
HLT_Mu30_TkMu11_v2
HLT_Mu40_TkMu11_v2
HLT_Mu20_v2
HLT_TkMu20_v2
HLT_Mu24_eta2p1_v2
HLT_TkMu24_eta2p1_v2
HLT_Mu27_v2
HLT_TkMu27_v2
HLT_Mu50_v2
HLT_Mu45_eta2p1_v2
HLT_Mu8_TrkIsoVVL_v2
HLT_Mu17_TrkIsoVVL_v2
HLT_Mu24_TrkIsoVVL_v2
HLT_Mu34_TrkIsoVVL_v2
HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v2
HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v2
HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v2
HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v2
HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v2
HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_v2
HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_v2
HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_v2
HLT_Ele23_CaloIdL_TrackIdL_IsoVL_v2
HLT_Ele17_CaloIdL_TrackIdL_IsoVL_v1
HLT_Ele12_CaloIdL_TrackIdL_IsoVL_v2
HLT_Mu8_v2
HLT_Mu17_v2
HLT_Mu24_v2
HLT_Mu34_v2
HLT_Mu55_v1

Further restrictions (that will be needed if 2 more triggers might be added in the future) would be difficult in the sense of keeping all possible needs for analyses we currently do not know of. One example is the trigger efficiency study, which requires quite some different triggers than the baseline analysis.

Therefore I would like to bring this issue up here. If somebody has ideas how to overcome this artificial restriction, this would be highly appreciated. Otherwise we might have to do sub-analysis-dependent skims or maybe skims with sample-dependent triggers in the future, which I would like to avoid. For obvious reasone, the first would even spoil the memory consumption advantage of the restriction to 64 trigger bits.

Cheers,
Thomas

**Comment by rfriese** [comment]
solved on CMSSW80X branch
