### ISSUE TITLE
Changing hash used for identifying KMETs and introducing an Id for KLeptons

### ISSUE THREAD

**Issue by rcaspart** [KappaAnalysis/Kappa#20]
Dear all,

We found out that the current way of identifying the KMET belonging to a set of leptons (i.e. comparing the combination of the hashes returned by KLepton.getHash() [_] for the leptons to that of the Met) is not working deterministically for all events. This was traced back to a difference in the values returned by reco::LeafCandidate::mass() (used to fill the 4-momentum of the leptons [_]) and reco::LeafCandidate::p4().M() (used for the hash calculation of the met [**]).

After discussion with Andrew I would suggest the following changes to mitigate this problem and and also make the code more stable in terms of floating point precision (please keep in mind here that in Kappa we store float variables, whereas the objects on edm Level are double ones):
1) add an unsigned int internalId member to the KLeptons. This member is the hash of the pointer of the corresponding Lepton and can uniquely identify this lepton.
2) change the hash of the KMET to be the combined hash of the corresponding Leptons (as given in point 1). This can for example be done with boost::hash_combine [***].

These changes allow us to uniquely identify the Met belonging to a pair of selected leptons on analysis level just as before by combining the individual internalIds/hashed and comparing to that of the KMET. While not being sensitive to the actual 4-momentum of the leptons (this also means that the association is persistent for the case of applying corrections to the 4-momenta without the need to create a map for associating the corrected and uncorrected ones).

Cheers,
Rene

[_] https://github.com/KappaAnalysis/Kappa/blob/CMSSW_7_6_X/DataFormats/interface/KLepton.h#L90
[__] https://github.com/KappaAnalysis/Kappa/blob/CMSSW_7_6_X/Producers/interface/KPatMETsProducer.h#L49
[_**] http://www.boost.org/doc/libs/1_35_0/doc/html/boost/hash_combine_id241013.html

**Comment by FredStober** [comment]
Hi, CMSSW changed between CMSSW_7_3_5 and CMSSW_7_4_0 the pt, eta, phi, M data type of the edm objects from float to double. Maybe this should be done in Kappa as well?
