### ISSUE TITLE
Polymorphic dataformat types

### ISSUE THREAD

**Issue by thomas-mueller** [KappaAnalysis/Kappa#23]
I would like to use `dynamic_cast` to identify the actual types of objects of Kappa dataformats. As an example, the `static_cast` [here](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/src/Utility/GeneratorInfo.cc#L39-L47) does not give the desired result, whereas `dynamic_cast` does.

Currently it is not possible to `dynamic_cast` objects of Kappa dataformats, because the types are not polymorphic. On [stackoverflow](http://stackoverflow.com/questions/8469900/cant-downcast-because-class-is-not-polymorphic/8469954#8469954) it is explained that this is due to the lack of virtual functions and it is suggested to add virtual destructors. I tested this in the `struct KGenParticle` and was then able to exchange the `static_cast` in the example above by a `dynamic_cast`.

Therefore I would like to understand, if there are any problems expected with such a change. I will test as well, wether the skim still works with such changes in the dataformats and I will then propose a pull request in the next time. Comments and explanations are very welcome.

**Comment by FredStober** [comment]
Polymorphic types have a hidden vtable to make this possible. The virtual method dispatch also introduces overhead for calls. For your type of datasets, this runtime and storage overhead is probably not important. It is likely that doing it properly would impact your data model more than you want.

**Comment by thomas-mueller** [comment]
Can you elaborate a bit more on your last sentence?

**Comment by rfriese** [comment]
why do you even have to cast? To me, things like returning a moment look like typical functionalities every object should bring with themselves. Maybe the proper way to go would be to unify KParticle and KGenTau? I think this would be a good Idea anyway due to the overlap in the "is..." functions.

**Comment by FredStober** [comment]
Kappa was originally designed to avoid depending on RTTI - if you need to do it (as in your example) this is due to the design of the data scheme / data processing chain (and I don't think you want to change that). So the answer is: making it polymorphic will solve your problem - with a certain performance cost, that is likely irrelevant in your case.

**Comment by thomas-mueller** [comment]
@rfriese: In this special example (is not the single one that exists) I am talking about KGenParticle and KGenTau (not KParticle). And both have a p4 member. Additionally, KGenTau has a vis_p4 member, which is needed in my example in some cases.

**Comment by FredStober** [comment]
If you want a discussion about RTTI, you can look at:
http://www.gamedev.net/topic/667649-is-c-rtti-good-or-bad
http://stackoverflow.com/questions/5134975/what-can-make-c-rtti-undesirable

**Comment by rfriese** [comment]
Sorry, I meant unify KGenTau and KGenParticle.

It would solve all these casting problems with nearly no cost - just leave the visible momentum at 0 if its the same as the p4 itself, allowing root to compress it away and access the visible pt itself only via a getter function. You would  save filling the m_ptOrderedGenLeptonVisibleLVs at all since it will become a member function of the members of m_ptOrderedGenLeptons.

Just saying, casting sure also does the job...

**Comment by thomas-mueller** [comment]
I am more in favour of a cleaner solution instead of leaving members of dataformats empty. But what do others think?

**Comment by thomas-mueller** [comment]
The other thing is, that this proposal would require a dict change and therefore a new skim. Additionally, this is a lot of work, since in principle one would then have to think about removing the complete class hierachy.

**Comment by rfriese** [comment]
a solution like this is not necessarily unclean if you do something like

private:
    RMFLS m_visp4;
public:
RMFLV getVisMomentum(){
if (m_visp4 = RMFLV(0,0,0,0)) /// or something equivalent like asking if it's not a tau
    return p4;
else
    return m_visp4;
}

doesn't adding a virtual constructor also mean a dict change?

**Comment by thomas-mueller** [comment]
4 float comparisons are not unclean???

I checked it that adding the destructor does not mean a dictchange.

**Comment by anehrkor** [comment]
If I understand this correctly, you would want to give KGenParticle a member vis_p4 regardless of the type of gen particle, right? I don't like this very much. I think a class should only have as many members as it needs. If there is an object that needs all of these members but one more, it should become a new class inheriting from the other class.

**Comment by maxfischer2781** [comment]
4 float comparisons are not unclean, they are an implementation detail.

IMO the problem starts with GeneratorInfo [mucking around](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/src/Utility/GeneratorInfo.cc#L34) in implementation details of the two classes. It's pretty much already a getter (what Raphael proposes) but on an unrelated object. Especially if this is needed at multiple points of working with KGenParticle, it's obviously part of KGenParticle's responsibility.

**Comment by maxfischer2781** [comment]
On a sidenote, this is probably how TH1 got its y and z axis... _hint__hint_

**Comment by thomas-mueller** [comment]
I always considered `TH1::GetYaxis` as a bad style. Do you, Max (with more knowledge than me) now want to tell me, that this is the way to go?

And what do you mean by "a getter on an unrelated object"? What would be the unrelated object? You mean something else telling you whether it is a KGenParticle or a KGenTau?

**Comment by anehrkor** [comment]
A KGenTau is very different from any other KGenParticle as it features also decay modes for example. And while returning for example the full p4 as vis_p4 of a KGenParticle might be ok if it's not a KGenTau (it physically makes sense), returning dummy values for the decay properties would be at least confusing. So I would really recommend keeping KGenTau as an ancestor of KGenParticle.

I agree that the consequence of having to do class-dependent implementation is not nice but I think it's the lesser evil :)

**Comment by maxfischer2781** [comment]
Adding `KGenParticle::getVisMomentum` - yeah, that feels like `TH1::GetYaxis`. Not like the `TH1::GetYaxis` used by thousands of people, but something that will get you there eventually. Root-of-all-evil, haha, etc.

However, you already do have `TH1::GetYaxis`, and it's called `GeneratorInfo::GetVisibleLV`.  `GeneratorInfo::GetVisibleLV` implements the functionality that Raphael proposed as `KGenParticle::getVisMomentum` (albeit implemented differently). If you can live with `GeneratorInfo::GetVisibleLV`, you should be able to live with `KGenParticle:: GetVisibleLV` even better.

BTW, for the short time being, using `dynamic_cast` in the implementation does seem like the cleaner way than empty members. Your use case is what it's there for.
The overhead for RTTI is not that bad. See also Fred's links
Long term, my question would be why you put objects with ambiguous definitions of P4 into the same buckets in the first place.

**Comment by thomas-mueller** [comment]
Thanks for the clearification!

The answer to your last sentence is based on the physics of H->tautau decays and there it totally makes sense (and was not even introduced by me).

**Comment by rfriese** [comment]
There's a lot mixed up here.

I stated "or something equivalent" that checks if its a tau, e.g. the pdgId, it's not necessarily the p4 that has to be compared. Really a detail.

I never said anything about _returning_ dummy values. A user will never be able to retrieve an empty value if interfaces are created properly.

The KGenparticle has the following functions:
https://github.com/KappaAnalysis/Kappa/blob/master/DataFormats/interface/KParticle.h#L124-L134
If you split everything e.g. by the pdgId most of these functions also do not make sense any more. Same way, all "is.." functions that currently are part of the GenTau return "false" if they would be part of the KGenParticle.

Anyway, both collections are calculated from the reco::genParticles collection. Atm we split this collection up in Kappa in GenParticles and GenTaus, then put them in the same lists in Artus. Then we realize they are not the same and again cast them. This to me seems like historically grown; if you think about it you would never write it that way from front to end.

**Comment by thomas-mueller** [comment]
Thanks also to Raphael for the clearification. Together with Max's comments, the picture is now sufficiently clear to me.

I understand to aim of Raphael to use what is already there (e.g. the `KGenParticle::is...()` functions). On the other hand I do not (yet) see strong support for the merging of (base und sub) classes and therefore for progressively removing the class hierarchy. (A personal comment: I have problems with accepting the tendency to non-filled members of classes instead of using the upper class dataformats, see https://github.com/KappaAnalysis/Kappa/issues/13. The way it is done now it very hard to find out on analysis level, wether a for example a vector is empty because there was no such particle or just because this information is just not available in miniAOD. But maybe a better way to transport/document this information would already help.)

For these reasons I made the following checks in my actual example (where I am not so sure, whether this issue is the right place to explain it):

The [function](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/src/Utility/GeneratorInfo.cc#L34-L50) `GeneratorInfo::GetVisibleLV` gets a KGenParticle as a parameter, which in my example is actually the return value of the [function](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/src/Utility/GeneratorInfo.cc#L52-L82) `GeneratorInfo::GetGenMatchedParticle`. As also pointed out by Max (and Fred), the `dynamic_cast` seems to be the most appropriate approach, because this is the way to probe the special type of the return value of the second function.

In order to avoid changes in Kappa and live with the existing code as proposed by Raphael (I neglect the option to merge classes of the dataformat, because this requires dictchange and a new skim and is therefore much more complication and work), I compared the output of

``` c++
genParticle->isDirectPromptTauDecayProduct()
(! genParticle->isDirectPromptTauDecayProduct())
(std::abs(genParticle->pdgId) == DefaultValues::pdgIdTau)
(std::abs(genParticle->pdgId) != DefaultValues::pdgIdTau)
```

with the one of

``` c++
(genTau != nullptr)
```

which is what I need in [line 40](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/polymorphic_dataformats/src/Utility/GeneratorInfo.cc#L40) (on the polymorphic_dataformats branch). I see, that none of these four bools is 100% correlated with `(genTau != nullptr)` and therefore conclude, that I cannot use them, at least not in this easy way.

My conclusion is, that I have to use the `dynamic_cast` and therefore I will create a pull requested here in the next hours. I think we can consider this issue then as close and might discuss the pull request (if needed).

**Comment by FredStober** [comment]
I think raphael pointed out nicely what i meant with my first comment(s):

Raphael:

> Anyway, both collections are calculated from the reco::genParticles collection. Atm we split this collection up in Kappa in GenParticles and GenTaus, then put them in the same lists in Artus. Then we realize they are not the same and again cast them. This to me seems like historically grown; if you think about it you would never write it that way from front to end.

My 2nd comment:

> Kappa was originally designed to avoid depending on RTTI - if you need to do it (as in your example) this is due to the design of the data scheme / data processing chain

My 1st comment:

> It is likely that doing it properly would impact your data model more than you want.

I guess what I want to say is: Make the Kappa classes polymorphic and use "dynamic_cast" - but be aware that you are working around a bad design in the artus analysis in that case. To cite my link above (sic):

> Even needing to use these features in the first place is a "code smell" though - a hint that your algorithm/code is ill thought out. There's usually better solutions that dojt involve using RTTI.
