### ISSUE TITLE
Some older samples have nicknames without extension

### ISSUE THREAD

**Issue by anehrkor** [KappaAnalysis/Kappa#25]
So far, we found two samples that have nicknames that do not have "extX" in their name. This results in problems during the [query](https://github.com/KappaAnalysis/Kappa/blob/master/Skimming/python/registerDatasetHelper.py#L233). The extension entry was therefore manually removed from [these samples](https://github.com/KappaAnalysis/Kappa/commit/56b40569696c58aac98752d1e7d7d56d2bb47b7e) in order to be backward compatible.

Should you encounter problems like the following, you can try to remove the extension of the affected sample in datasets.json.

The following query expected 1 samples, but found 0:
{‚campaign‘: ‚RunIIFall15MiniAODv2‘,
 ‚energy‘: ‚13‘,
 ‚extension‘: ‚‘,
 ‚format‘: ‚MINIAOD‘,
 ‚generator‘: ‚madgraph-pythia8‘,
 ‚process‘: ‚DYJetsToLLM50‘,
 ‚scenario‘: ‚PU25nsData2015v1‘}
found the following matching samples:
[]

**Comment by rfriese** [comment]
@anehrkor this is solved, right?
