### ISSUE TITLE
Error in <TClass::LoadClassInfo>: no interpreter information for class KProvenance is available eventhough it has a TClass initialization routine.

### ISSUE THREAD

**Issue by thomas-mueller** [KappaAnalysis/Kappa#30]
Dear experts,

we are getting the error

```
Error in <TClass::LoadClassInfo>: no interpreter information for class KProvenance is available eventhough it has a TClass initialization routine.
```

when loading an arbitrary Kappa file in Artus using ROOT 6. This is followed by a segmentation fault. For reasons, that are not yet clear to me, this error only appears in (all) Jobs running at the RWTH Tier2. Does anybody have an idea (or hint) what could cause this problem? Most probably this is related to ROOT 6.

Regards,
Thomas

**Comment by rfriese** [comment]
There was a files missing to be sent with the job
https://github.com/artus-analysis/Artus/commit/9ef59d2bc47f5739476baabe78014032937bce23

**Comment by thomas-mueller** [comment]
Thanks Raphael, this works. I would have never guessed this.

What is the reason why we need this now?

**Comment by rfriese** [comment]
A few lines above the error you posted, it was complaining that this file is missing. And indeed, it is there in the externals directory but was not in the sandbox.

I don't know what it does...

**Comment by thomas-mueller** [comment]
Ah, I missed this. The matching file names contain "dict". So I assume it is related to the ROOT dictionaries.

(Indeed, the output of Artus gets longer and longer and we get trained in ignoring warning, that are actually not warnings. Shouldn't we put more into debug logging level and remove unnecessary warnings?)

**Comment by rcaspart** [comment]
Just for completeness:
the pcm files are part of roots way of working with dictionaries/libraries and new since root 6. They are created by the "rootcint" call to generate the dictionary. As far as I know these files contain additional metadata which root requires for working with corresponding classes.
