### ISSUE TITLE
Memoryleak in KPatJetProducer

### ISSUE THREAD

**Issue by FredStober** [KappaAnalysis/Kappa#35]
8ae9dd7a6a46452add98296d11c3a02b417c8666 introduced and 76fcf8f73249601a7867dd95846e4fe9134a99eb enabled a memory leak.
When running on data (or without gen matching), this line:
https://github.com/KappaAnalysis/Kappa/blob/master/Producers/interface/KPatJetProducer.h#L148
leaks a reco::GenJet for every jet in the dataset. I guess there is some reason why there isn't just an if (in.genJet() != nullptr) around the fillGenJet (and else set to 0)?
It is *never* a good idea to insert a new without adding a delete...

**Comment by rfriese** [comment]
should be solved:
https://github.com/KappaAnalysis/Kappa/commit/f51ebae1ecd558bd57fca3230795a66e117afc5f
