### ISSUE TITLE
Skimming check out 

### ISSUE THREAD

**Issue by swayand** [KappaAnalysis/Kappa#40]
Hi,

are this lines still be needed:
https://github.com/KappaAnalysis/Kappa/blob/dictchanges/Skimming/scripts/checkoutCmssw80xPackagesForSkimming.py#L69
and 
https://github.com/KappaAnalysis/Kappa/blob/dictchanges/Skimming/scripts/checkoutCmssw80xPackagesForSkimming.py#L88-L93

following:
https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1861/1/1/1.html
the changes should be all migrated into the CMSSW_8_0_26_patch1 release. So maybe one could start a clean up.

**Comment by anehrkor** [comment]
The cut-based electron Id seems to be in CMSSW_8_0_26. I don't know about the MVA-based Id though. You can test this of course by checking out RecoEgamma/ElectronIdentification in your 8_0_26/src area and checking if the xml files are there or not.

**Comment by rfriese** [comment]
It's now rather time to switch to a newer CMSSW80X release where the temporary changes are picked up. This might also allow Kappa to compile in time.
