### ISSUE TITLE
Inconsistent dataset queries

### ISSUE THREAD

**Issue by thomas-mueller** [KappaAnalysis/Kappa#46]
The functions [`registerDatasetHelper.get_sample_by_nick`](https://github.com/KappaAnalysis/Kappa/blob/master/Skimming/python/registerDatasetHelper.py#L281-L301) and [`datasetsHelperTwopz.datasetsHelperTwopz.get_nicks_with_regex`](https://github.com/KappaAnalysis/Kappa/blob/master/Skimming/python/datasetsHelperTwopz.py#L161-L170) do the transition from nick names to datasets stored in datasets.json. In some cases they find different/inconsistant match results, although they are used for the same purpose. This should be unified.

**Comment by thomas-mueller** [comment]
A more detailed description of the issue is found here: https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/issues/55.

**Comment by ArturAkh** [comment]
https://github.com/KappaAnalysis/Kappa/commit/7340ec3baaaf27df6ce6143216c074a8d0ef3421

**Comment by thomas-mueller** [comment]
The result of the other version was the "correcter" one:

```bash
HiggsToTauTauAnalysis.py @HiggsAnalysis/KITHiggsToTauTau/data/ArtusWrapperConfigs/Run2CPStudies_Nominal.cfg -i HiggsAnalysis/KITHiggsToTauTau/data/Samples/XROOTD_sample_GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg_recent.txt -f 1 
Error: expected and retrieved number of matching nicknames aren't equal.
```

I fear this commit needs to be reverted.

**Comment by thomas-mueller** [comment]
https://github.com/KappaAnalysis/Kappa/commit/a1333d8b233d95ad89cf4bfd57dcb1202289355d
