### ISSUE TITLE
quantity "sigma" in the PileupDensityProducer

### ISSUE THREAD

**Issue by rfriese** [KappaAnalysis/Kappa#47]
Hi all,

I'm currently switching from getByLabel to getByToken. I noticed that there is a "sigma" quantity, read out as a plain double value from the input. But - it does not use yet the consumescollector to register its input. This means it does not work now for more than 1.5years / CMSSW76X.

Does anyone still use this sigma quantity? Otherwise I'll just remove it.

Cheers

https://github.com/KappaAnalysis/Kappa/blob/master/Producers/interface/KPileupDensityProducer.h#L30-L35

**Comment by greyxray** [comment]
Hi Raphael! 

I might have missed something but isn't it so that if the object is not registered it can not be used later? If yes then probably nobody is using it now

**Comment by rfriese** [comment]
yes, that's the point. I just wanted to make you aware not to delete anything that is at least planned to be brought back.
In the meantime I discovered that probably the same is true for the FilterSummaryProducer. It works to count the number of events, but not to write out what is pre-registered in the MiniAOD file. Also, no one has touched the config in 5 years.

**Comment by greyxray** [comment]
I think in general it's better to be able to choose whether to store short or sustainable objects. 
In the case of sigma this is only 1 additional float. Is it acceptable to fix the registration instead?
Or maybe you are aware of a more elegant way to do this rather than deleting code? (same about FilterSummaryProducer I think)

**Comment by rfriese** [comment]
well, many things have changed in the transition to MiniAOD ( and pat objects). So they are stored in a more clever way and not distributed among many collections any more.

In the KITHiggs Repo I could not find that sigma from the PileupDensity is used. To be honest I don't even know what this variable should mean...

In the FilterSummaryProducer I won't delete code but deactivate it. Especially when starting with Kappa I don't want to confuse people with code parts that are never used. It blows Kappa up and due to heavy use of templates blows up the compile time.
