### ISSUE TITLE
Transition to "slimmedPatTrigger" breaks backward compatibility

### ISSUE THREAD

**Issue by dsavoiu** [KappaAnalysis/Kappa#49]
The default Kappa config was updated to use "slimmedPatTrigger" instead of "selectedPatTrigger":

https://github.com/KappaAnalysis/Kappa/blame/f51ebae1ecd558bd57fca3230795a66e117afc5f/Producers/python/KTuple_cff.py#L113

This breaks backward compatibility with CMSSW_8_0_X. When skimming 80X miniAODs (Run2016), the following error occurs:

```
Begin processing the 1st record. Run 277126, Event 1238371, LumiSection 18 at 22-Jul-2017 01:13:53.609 CEST
Could not get main product! triggerObjects.src = slimmedPatTrigger
```

One way to get around this is to overwrite the key in all 80X skimming configs:

```
process.kappaTuple.TriggerObjectStandalone.triggerObjects = cms.PSet(
        src=cms.InputTag("selectedPatTrigger")
)
```

Not sure what the policy for the default Kappa config is... Is it generally supposed to work only for the newest CMSSW/miniAOD version? If yes, is patching the 80X configs the preferred way of keeping backwards compatibility?

**Comment by rfriese** [comment]
Hi Daniel,

I recommend the solution in your commit 968d4589.

The default should always be the most up-to-date ones. Otherwise we end up patching together the most recent version and no one knows when to change the defaults, that might even be already invalid for years.

Cheers
