### ISSUE TITLE
Could not get main product! LHEafter.src = externalLHEProducer

### ISSUE THREAD

**Issue by rfriese** [KappaAnalysis/Kappa#52]
Dear all,

for quite some time we get the error

"Could not get main product! LHEafter.src = externalLHEProducer"

When running Kappa on the test file (plain cmsRun kSkimming_run2_cfg.py).

I don't know what the LHE module is supposed to do, but atm it for sure does not work properly since this collection is missing. I also see nothing that is able to produce a collection called "externalLHEProducer".

Might it be safe to disable the LHE Producer for the Higgs analysis? Or will someone take care of it?

Cheers,
Raphael

**Comment by thomas-mueller** [comment]
Dear Raphael,

we need the LHE particles for the CP analyses. Therefore we cannot switch off this producers. I guess that @jd550179 will check this and come up with a solution. But this might take some time as it is vacation/exam time now...

Regards,
Thomas
