### ISSUE TITLE
Issue with CMSSW data access in 7_6_0

### ISSUE THREAD

**Issue by ajgilbert** [KappaAnalysis/Kappa#6]
Hi Kappa developers,

 I noticed a problem testing some code in 7_6_0: it is now required to use the consumes mechanism to register for data access in all CMSSW modules. See more details in the hn [here](https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3428/1.html) and the twiki page [here](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent#Consumes_and_Helpers). 
It's not too much trouble to update code to use this mechanism but the problem comes with wanting to support older CMSSW releases, e.g. the 5_3_X series, which don't have this functionality. While it would be possible to work around this with a heavy amount of `#if CMSSW_MAJOR_VERSION` checks this clearly isn't a nice solution. Did anyone else look into this yet? Maybe it would be good to discuss at some point, since we'll need this release for the re-reco.

cheers,
Andrew

**Comment by FredStober** [comment]
A helper function to get an edm Handle in the BaseProducer seems like the most consistent solution. The macro checks to differentiate between the different CMSSW versions would only appear in that function.

**Comment by rfriese** [comment]
solved since 76X
